var jan_es = new Array();
jan_es.push("D&iacute;a de A&nacute;o Nuevo");
jan_es.push("Representar una historia favorita. Use t&iacute;teres, mu&nacute;ecas o animales de peluche.");
jan_es.push("Haga que su hijo dividir un aperitivo para compartir uniformemente.");
jan_es.push("Leer dos libros hoy");
jan_es.push("No hay actividad para hoy");
jan_es.push("Semana Azul: buscar las cosas que son de color azul esta semana.");
jan_es.push("No hay actividad para hoy");
jan_es.push("Cantar algunas de las canciones favoritas de su hijo.");
jan_es.push("No hay actividad para hoy");
jan_es.push("D&iacute;a de la Biblioteca!");
jan_es.push("Juego Simon Says.");
jan_es.push("Jugar juegos de contar como '&iquest;Cu&aacute;ntas cosas azules es lo que ves?' No hay operaci&oacute;n por Hoy");
jan_es.push("Ayude a su hijo a hacer su / su s&aacute;ndwich favorito.");
jan_es.push("No hay actividad para hoy");
jan_es.push("Continuar ense&nacute;ar a su hijo a su / su n&uacute;mero de tel&eacute;fono y direcci&oacute;n.");
jan_es.push("No hay actividad para hoy");
jan_es.push("Ense&nacute;e a su hijo a jugar un juego de mesa con un amigo.");
jan_es.push("Hacer una hucha jun_estos de una lata de caf&eacute; y comience a ahorrar monedas.");
jan_es.push("Recite rimas infantiles con su ni&nacute;o.");
jan_es.push("Encontrar cosas en la casa que comiencen con el mismo sonido de la letra. Nombre de la letra.");
jan_es.push("mar_estin Luther King, Jr.");
jan_es.push("Juegue 'I Spy n&uacute;meros.' No hay actividad para hoy");
jan_es.push("No hay actividad para hoy");
jan_es.push("D&iacute;a de la Biblioteca!");
jan_es.push("No hay actividad para hoy");
jan_es.push("Hacer o hacer un mu&nacute;eco de nieve con su hijo.");
jan_es.push("El uso de un art&iacute;culo de prensa, las palabras c&iacute;rculo que comienzan con la primera letra del nombre de su hijo.");
jan_es.push("No hay actividad para hoy");
jan_es.push("Practique contar hasta 10 o superior.");
jan_es.push("No hay actividad para hoy");
jan_es.push("No hay actividad para hoy");

var feb_es = new Array();
feb_es.push("Leer un libro sobre los sentimientos.");
feb_es.push("Atrapado en el tiempo");
feb_es.push("Semana Red: buscar las cosas que son de color rojo esta semana.");
feb_es.push("Encontrar cosas en la casa que comiencen con el sonido de la letra 'M' no hay operaci&oacute;n por Hoy");
feb_es.push("No hay actividad para hoy");
feb_es.push("Haga una lista de las personas que amas y hablar acerca de por qu&eacute; usted los ama.");
feb_es.push("D&iacute;a de la Biblioteca!");
feb_es.push("Hacer y enviar caseras tarjetas de San Valent&iacute;n a sus seres queridos en su lista.");
feb_es.push("No hay actividad para hoy");
feb_es.push("A&nacute;o Nuevo Chino");
feb_es.push("Hacer t&iacute;teres con bolsas de papel o calcetines y representar una actividad divertida.");
feb_es.push("Cumplea&nacute;os de Lincoln");
feb_es.push("Leer un cuento y p&iacute;dale a su hijo lo que su / su parte favorita era y por qu&eacute;");
feb_es.push("D&iacute;a de San Valent&iacute;n");
feb_es.push("Comprime! Lleve a su hijo a caminar e invitar a un amigo");
feb_es.push("Contar todas las puertas y ventanas de su casa.");
feb_es.push("Jugar a un juego de mesa o juego de cartas con su hijo.");
feb_es.push("Cumplea&nacute;os de Washington D&iacute;a de los Presidentes");
feb_es.push("Canta la canci&oacute;n del abecedario.");
feb_es.push("Haga que su hijo invite a un amigo a jugar.");
feb_es.push("D&iacute;a de la Biblioteca!");
feb_es.push("No hay actividad para hoy");
feb_es.push("Mira afuera y hablar sobre lo que ve.");
feb_es.push("Recuerde consultar con su escuela para las fechas de registro de kindergarten.");
feb_es.push("No hay actividad para hoy");
feb_es.push("No hay actividad para hoy");
feb_es.push("Invite a un amigo para asistir a Read Across America at Lincoln Square con usted.");
feb_es.push("No hay actividad para hoy");
feb_es.push("No hay actividad para hoy");

var mar_es = new Array();
mar_es.push("Escuchar una historia en cinta o CD con su hijo.");
mar_es.push("Read Across America");
mar_es.push("Semana Purple: buscar las cosas que son p&uacute;rpuras esta semana.");
mar_es.push("Haga que su hijo practique saltar, saltar en un pie, y lanzar y atrapar una pelota.");
mar_es.push("Programe un examen f&iacute;sico y dental guarder&iacute;a para su hijo.");
mar_es.push("No hay actividad para hoy");
mar_es.push("D&iacute;a de la Biblioteca!");
mar_es.push("Continuar ense&nacute;ar a su hijo a su / su n&uacute;mero de tel&eacute;fono y direcci&oacute;n.");
mar_es.push("No hay actividad para hoy");
mar_es.push("El horario de verano comienza relojes vuelta una hora hacia adelante");
mar_es.push("Cantar canciones con sonidos que riman.");
mar_es.push("Nombra una carta y pida a su hijo a encontrar los elementos que comienzan con ese sonido.");
mar_es.push("Corte formas y jugar un juego de correspondencias.");
mar_es.push("Inventa palabras chistosas que rimen con el nombre de su hijo.");
mar_es.push("Leer dos libros hoy. Haga que su ni&nacute;o le diga que es su / su favorito y por qu&eacute;");
mar_es.push("No hay actividad para hoy");
mar_es.push("D&iacute;a de San Patricio");
mar_es.push("Buscar las cosas de la casa que comiencen con el sonido de la letra 'J' no hay operaci&oacute;n por Hoy");
mar_es.push("No hay actividad para hoy");
mar_es.push("Primavera comienza Tome un paseo y buscar signos de la primavera.");
mar_es.push("D&iacute;a de la Biblioteca!");
mar_es.push("No hay actividad para hoy");
mar_es.push("Opuestos practicar con su hijo (arriba / abajo, dentro / fuera, encima / por debajo)");
mar_es.push("No hay actividad para hoy");
mar_es.push("Pascua comienza al atardec_eser");
mar_es.push("Encuentra cosas que empiezan con el sonido de la letra 'D.' No Actividad para hoy");
mar_es.push("Representar ir al m&eacute;dico o al dentista. Hable acerca de lo que podr&iacute;a suceder.");
mar_es.push("Hornear galletas jun_estos. Cuente el n&uacute;mero en cada bandeja");
mar_es.push("Viernes Santo ");
mar_es.push("No hay actividad para hoy");
mar_es.push("Domingo de Pascua ");

var apr_es = new Array();
apr_es.push("D&iacute;a de los Inocentes Lunes de Pascua");
apr_es.push("Mantenga el televisor apagado hoy. Leer libros y juegos de juego en su lugar.");
apr_es.push("No hay actividad para hoy");
apr_es.push("D&iacute;a de la Biblioteca! Trae un amigo a la biblioteca y ver una pel&iacute;cula jun_estos.");
apr_es.push("Haga que sus letras Nombre del ni&nacute;o que se encuentra en las cajas de cereal, latas, etc");
apr_es.push("No hay actividad para hoy");
apr_es.push("Visite el sitio web de PBS: www.pbskids.org.");
apr_es.push("Haz un dibujo de la primavera.");
apr_es.push("No hay actividad para hoy");
apr_es.push("No hay actividad para hoy");
apr_es.push("No hay actividad para hoy");
apr_es.push("No hay actividad para hoy");
apr_es.push("Practique impresi&oacute;n trazando las letras del nombre de su hijo en un pedazo de papel.");
apr_es.push("Semana del Ni&nacute;o Peque&nacute;o comienza");
apr_es.push("Preg&uacute;ntele a su D&iacute;a de la Biblioteca! Bibliotecario que le recomiende la m&uacute;sica de los nuevos ni&nacute;os.");
apr_es.push("No hay actividad para hoy");
apr_es.push("Visita www.pbs.org / padres y hacer clic en â € œFun y Gamesa €? tab.");
apr_es.push("D&iacute;a Libary! Deje que su hijo escoja un video de toda la familia podr&aacute; disfrutar.");
apr_es.push("Leer dos libros hoy. Haga que su ni&nacute;o escoja los libros.");
apr_es.push("Cantar una canci&oacute;n favorita de su hijo.");
apr_es.push("No hay actividad para hoy");
apr_es.push("D&iacute;a de la Tierra");
apr_es.push("Vea televisi&oacute;n con su hijo, hable acerca de lo que ve y siente, y hacer preguntas.");
apr_es.push("Ponga m&uacute;sica y baile y palmas al comp&aacute;s.");
apr_es.push("No hay actividad para hoy");
apr_es.push("No hay actividad para hoy");
apr_es.push("Haga que su ni&nacute;o comience a apr_esender su / su fecha de nacimiento y la edad.");
apr_es.push("Semana Pink: buscar las cosas que son de color rosa esta semana.");
apr_es.push("Salga a caminar y hablar acerca de los diferentes sonidos que se escuchan");
apr_es.push("No hay actividad para hoy");
apr_es.push("No hay actividad para hoy");

var may_es = new Array();
may_es.push("No hay actividad para hoy");
may_es.push("D&iacute;a de la Biblioteca!");
may_es.push("Juego Simon Says. Centrarse en las actividades del ejercicio (saltar, agacharse, tocar los dedos del pie).");
may_es.push("No hay actividad para hoy");
may_es.push("Cinco de may_eso");
may_es.push("Encontrar cosas en la casa que son cuadrados, circulares y rectangulares.");
may_es.push("No hay actividad para hoy");
may_es.push("Encuentra cosas que empiezan con el sonido de la letra 'L.' Diga el nombre de la letra.");
may_es.push("Invente rimas sin sentido y re&iacute;r jun_estos.");
may_es.push("Nombre palabras que riman con 'can'.");
may_es.push("No hay actividad para hoy");
may_es.push("D&iacute;a de la Madre");
may_es.push("No hay actividad para hoy");
may_es.push("Ayude a su hijo a escribir su / su nombre.");
may_es.push("No hay actividad para hoy");
may_es.push("D&iacute;a de la Biblioteca!");
may_es.push("Ordena monedas en grupos seg&uacute;n el color o el tama&nacute;o.");
may_es.push("No hay actividad para hoy");
may_es.push("Contar del 1 al 10 o tan alto como su hijo pueda contar.");
may_es.push("Ayude a su hijo a practicar zapato atado.");
may_es.push("No hay actividad para hoy");
may_es.push("Despu&eacute;s de escuchar una historia, haga que su ni&nacute;o le cuente lo que pas&oacute; primero, despu&eacute;s y &uacute;ltimo.");
may_es.push("Play 'I Spy'. (Recuerde incluir objetos negros.)");
may_es.push("Practicar la canci&oacute;n del abecedario.");
may_es.push("Juega un juego en conjun_esto, como la memoria o Go Fish.");
may_es.push("Semana Negro: buscar las cosas que son de color negro esta semana.");
may_es.push("D&iacute;a Conmemorativo");
may_es.push("No hay actividad para hoy");
may_es.push("Mira a trav&eacute;s de revistas viejas y cortar c&iacute;rculos, cuadrados y rect&aacute;ngulos.");
may_es.push("D&iacute;a de la Biblioteca!");
may_es.push("No hay actividad para hoy");

var jun_es = new Array();
jun_es.push("Encuentra cosas que empiezan con el sonido de la letra 'S' no hay operaci&oacute;n por Hoy");
jun_es.push("Semana Blanca: buscar las cosas que son de color blanco esta semana.");
jun_es.push("No hay actividad para hoy");
jun_es.push("Recordatorio: &iquest;Se planifica un jard&iacute;n de infantes examen f&iacute;sico y dental?");
jun_es.push("Planta flores jun_estas en una maceta o en el suelo y el agua de las flores.");
jun_es.push("Salir a la calle y preguntar a su ni&nacute;o que repita patrones: paso a paso-salto, clap-clap-pat, etc");
jun_es.push("P&iacute;dale a su hijo a hablar de los pasos en el proyecto de plantaci&oacute;n.");
jun_es.push("No hay actividad para hoy");
jun_es.push("Iniciar una canci&oacute;n de cuna y que su hijo termine.");
jun_es.push("Haga que su hijo invite a un amigo a jugar.");
jun_es.push("No hay actividad para hoy");
jun_es.push("Cortar una vieja tarjeta de felicitaci&oacute;n con forma de puzzle como. P&iacute;dale al ni&nacute;o que encajar las piezas de nuevo jun_estos.");
jun_es.push("D&iacute;a Libary!");
jun_es.push("D&iacute;a de la Bandera");
jun_es.push("Hacer un picnic con su hijo y comer fuera.");
jun_es.push("D&iacute;a del Padre");
jun_es.push("Al escoger las frutas y verduras en el supermercado, p&iacute;dale a su hijo el nombre de los colores.");
jun_es.push("No hay actividad para hoy");
jun_es.push("Leer un cuento a su hijo. Se&nacute;ale cada palabra a medida que lee.");
jun_es.push("Contar grupos de diez con cereales como Cheerios ™");
jun_es.push("Comienza Summer");
jun_es.push("Haz un dibujo de cosas divertidas que hacer en el verano.");
jun_es.push("No hay actividad para hoy");
jun_es.push("No hay actividad para hoy");
jun_es.push("Haga que sus calcetines partidos menores como doblar la ropa");
jun_es.push("Practique su n&uacute;mero de tel&eacute;fono y direcci&oacute;n.");
jun_es.push("D&iacute;a de la Biblioteca!");
jun_es.push("No hay actividad para hoy");
jun_es.push("No hay actividad para hoy");
jun_es.push("No hay actividad para hoy");
jun_es.push("No hay actividad para hoy");

var jul_es = new Array();
jul_es.push("No hay actividad para hoy");
jul_es.push("Encuentra cosas que empiezan con el sonido de la letra 'T' no hay operaci&oacute;n por Hoy");
jul_es.push("No hay actividad para hoy");
jul_es.push("D&iacute;a de la Independencia");
jul_es.push("Escoja dos libros para leer en la actualidad.");
jul_es.push("P&iacute;dale a su hijo a encontrar cosas que son su / su color favorito.");
jul_es.push("No hay actividad para hoy");
jul_es.push("No hay actividad para hoy");
jul_es.push("Salga a caminar y contar los &aacute;rboles u otras cosas que se ven.");
jul_es.push("No hay actividad para hoy");
jul_es.push("D&iacute;a de la Biblioteca!");
jul_es.push("Haz un dibujo de su familia y que su hijo diga los nombres y apellidos de cada miembro.");
jul_es.push("No hay actividad para hoy");
jul_es.push("No hay actividad para hoy");
jul_es.push("Practique escribiendo cartas y n&uacute;meros.");
jul_es.push("Encuentra objetos que riman con 'cerdo'.");
jul_es.push("No hay actividad para hoy");
jul_es.push("Haga que su ni&nacute;o le cuente una historia o evento en orden (primero, segundo, apellido).");
jul_es.push("No hay actividad para hoy");
jul_es.push("No hay actividad para hoy");
jul_es.push("Leer y hablar de la gente de otras culturas.");
jul_es.push("Cuente centavos ... contar lo m&aacute;s alto que pueda.");
jul_es.push("No hay actividad para hoy");
jul_es.push("Haga que su hijo invite a un amigo a jugar");
jul_es.push("D&iacute;a de la Biblioteca!");
jul_es.push("No hay actividad para hoy");
jul_es.push("Practique opuestos de nombres, como arriba / abajo, encendido / apagado, etc");
jul_es.push("No hay actividad para hoy");
jul_es.push("Salir a la calle y jugar a la rayuela o el swing.");
jul_es.push("No hay actividad para hoy");
jul_es.push("No hay actividad para hoy");

var aug_es = new Array();
aug_es.push("No hay actividad para hoy");
aug_es.push("Busque cosas que comienzan con 'P' Se&nacute;ale la letra 'P' en la impresi&oacute;n.");
aug_es.push("No hay actividad para hoy");
aug_es.push("Juegue 'I Spy Colores.' No hay actividad para hoy");
aug_es.push("Practique compresi&oacute;n y abotonar.");
aug_es.push("Leer un libro sobre ir a la escuela y pida a su hijo que vuelva a contar la historia");
aug_es.push("Visite a su nueva escuela y jugar en el parque infantil.");
aug_es.push("D&iacute;a de la Biblioteca!");
aug_es.push("Las palabras que rimen con 'me'.");
aug_es.push("No hay actividad para hoy");
aug_es.push("Haga de cuenta que es el primer d&iacute;a de clases. Maneras de dec_esir adi&oacute;s pr&aacute;ctica.");
aug_es.push("Practique rebotar una pelota. Cuente el n&uacute;mero de rebotes.");
aug_es.push("Organizar lo que necesitar&aacute; su hijo para el primer d&iacute;a de clases.");
aug_es.push("Practique tomar_es turnos y compartir.");
aug_es.push("Ayude a su hijo a escribir su / su nombre e identificar cada letra.");
aug_es.push("No hay actividad para hoy");
aug_es.push("No hay actividad para hoy");
aug_es.push("Practique su n&uacute;mero de tel&eacute;fono y direcci&oacute;n con su hijo.");
aug_es.push("No hay actividad para hoy");
aug_es.push("Haz un dibujo de tu nueva escuela.");
aug_es.push("No hay actividad para hoy");
aug_es.push("D&iacute;a de la Biblioteca!");
aug_es.push("No hay actividad para hoy");
aug_es.push("No hay actividad para hoy");
aug_es.push("No hay actividad para hoy");
aug_es.push("Usar la suma y la resta de palabras como 'Tengo una galleta y tiene dos cookies. Eso hace tres galletas.' No hay actividad para hoy");
aug_es.push("No hay actividad para hoy");
aug_es.push("No hay actividad para hoy");
aug_es.push("Armar_es un rompecabezas con su hijo.");
aug_es.push("No hay actividad para hoy");
aug_es.push("No hay actividad para hoy");

var sept_es = new Array();
sept_es.push("No hay actividad para hoy");
sept_es.push("Semana amar_esilla europea: buscar las cosas que son de color amar_esillo esta semana.");
sept_es.push("D&iacute;a del Trabajo!");
sept_es.push("Jugar a un juego de mesa o juego de cartas con su hijo.");
sept_es.push("Ayude a su hijo a escribir su / su nombre");
sept_es.push("No hay actividad para hoy");
sept_es.push("No hay actividad para hoy");
sept_es.push("No hay actividad para hoy");
sept_es.push("D&iacute;a Granparents '");
sept_es.push("Busque palabras que comienzan con la misma letra con libros, revistas y peri&oacute;dicos.");
sept_es.push("D&iacute;a del Patriota Visite el mercado de agricultores en el 201 W Kenyon en Champaign (1-5:30 pm).");
sept_es.push("Escoja un libro nuevo y anime a su ni&nacute;o a adivinar lo que la historia ser&aacute; sobre mirando la portada.");
sept_es.push("D&iacute;a de la Biblioteca! Lleve a su hijo a la biblioteca y obtener una tarjeta de biblioteca.");
sept_es.push("No hay actividad para hoy");
sept_es.push("Salga a caminar con su hijo. Hable acerca de lo que ve.");
sept_es.push("Rosh Hashan&aacute; comienza al ponerse el sol.");
sept_es.push("Encontrar los alimentos o animales que comienzan con el mismo sonido. Nombre de la letra.");
sept_es.push("Visite el mercado de agricultores en el 201 W Kenyon en Champaign (1-5:30 pm).");
sept_es.push("No hay actividad para hoy");
sept_es.push("No hay actividad para hoy");
sept_es.push("No hay actividad para hoy");
sept_es.push("Autumn Begins");
sept_es.push("No hay actividad para hoy");
sept_es.push("Practique contar del 1 al 10.");
sept_es.push("Yom Kipur comienza en el ocaso");
sept_es.push("No hay actividad para hoy");
sept_es.push("D&iacute;a de la Biblioteca! Haga que su hijo invite a un amigo a la biblioteca.");
sept_es.push("Mira a trav&eacute;s de revistas y libros para encontrar las cosas que son de color amar_esillo.");
sept_es.push("No hay actividad para hoy");

var oct_es = new Array();
oct_es.push("D&iacute;a de la Salud Infantil");
oct_es.push("Hable acerca de la ca&iacute;da y que su hijo haga un dibujo de un &aacute;rbol.");
oct_es.push("No hay actividad para hoy");
oct_es.push("Corte formas de papel para hacer una foto.");
oct_es.push("Si bien al aire libre, permitir&aacute; a su hijo a dibujar en la acera con tiza.");
oct_es.push("Vaya con su hijo a comprar para escribir y dibujar suministros.");
oct_es.push("Semana Naranja: buscar las cosas que son de color naranja esta semana.");
oct_es.push("D&iacute;a de la Raza");
oct_es.push("Recorte fotos de caras caras de revistas y hacer un collage sentimiento.");
oct_es.push("No hay actividad para hoy");
oct_es.push("D&iacute;a de la Biblioteca!");
oct_es.push("No hay actividad para hoy");
oct_es.push("Lleve a su hijo a caminar y recolectar diferentes tipos de hojas.");
oct_es.push("Lea el libro de sus hijos favoritos de su hijo.");
oct_es.push("No hay actividad para hoy");
oct_es.push("Visite el mercado de agricultores en el 201 W Kenyon en Champaign (1-5:30 pm).");
oct_es.push("Escribe una nota con su hijo a una gran-padre, pariente o amigo.");
oct_es.push("Organizar o contar cosas como calcetines, enlatados, sopas, botones, etc");
oct_es.push("No hay actividad para hoy");
oct_es.push("Concertar una cita para jugar para su hijo.");
oct_es.push("Ense&nacute;e a su hijo a escribir su / su nombre con letras may_es&uacute;sculas y min&uacute;sculas.");
oct_es.push("Haga una lista de compras jun_estos.");
oct_es.push("Buscar productos alimenticios o de los animales que empiezan con el mismo sonido que primero name.Name de su hijo de la letra.");
oct_es.push("No hay actividad para hoy");
oct_es.push("D&iacute;a de la Biblioteca!");
oct_es.push("Mira las im&aacute;genes de un libro con su hijo antes de leer");
oct_es.push("No hay actividad para hoy");
oct_es.push("No hay actividad para hoy");
oct_es.push("No hay actividad para hoy");
oct_es.push("Visite el mercado de agricultores en el 201 W Kenyon en Champaign (1-5:30 pm)");
oct_es.push("De Halloween");

var nov_es = new Array();
nov_es.push("D&iacute;a de Todos los Santos! Ayude a su ni&nacute;o a comenzar a apr_esender a su / su direcci&oacute;n y tel&eacute;fono");
nov_es.push("No hay actividad para hoy");
nov_es.push("Ayude a su ni&nacute;o que haga un dibujo de su familia.");
nov_es.push("El horario de verano! Gire clockers otro cambio horario.");
nov_es.push("Haga que su ni&nacute;o le cuente una historia a un miembro de la familia.");
nov_es.push("D&iacute;a de elecci&oacute;n");
nov_es.push("Tome un paseo. Encontrar cosas que son de color mar_esr&oacute;n.");
nov_es.push("Ponga m&uacute;sica y baile con su hijo y un amigo u otro miembro de la familia.");
nov_es.push("Semana Brown: Buscar cosas que son de color mar_esr&oacute;n esta semana.");
nov_es.push("Programe una cita para jugar en un parque");
nov_es.push("D&iacute;a de los Veteranos");
nov_es.push("Haga ejercicio con su hijo. Cuente el n&uacute;mero de c&iacute;rculos con los brazos o el l&uacute;pulo.");
nov_es.push("Jugar a la rayuela con su hijo.");
nov_es.push("P&iacute;dale a su hijo que le ayude a poner la mesa y contar los puntos.");
nov_es.push("D&iacute;a de la Biblioteca!");
nov_es.push("No hay actividad para hoy");
nov_es.push("Salir a la calle y patear una pelota de un lado a otro con su hijo.");
nov_es.push("Ir a la tienda y haga que su ni&nacute;o le ayude a recoger elementos para la acci&oacute;n de gracias.");
nov_es.push("Puedes buscar en libros, revistas de diferentes expresiones faciales: feliz, triste, emocionado, asustado, etc");
nov_es.push("No hay actividad para hoy");
nov_es.push("Hacer una fotograf&iacute;a o dec_esoraci&oacute;n de Acci&oacute;n de Gracias.");
nov_es.push("D&iacute;a de Acci&oacute;n de Gracias");
nov_es.push("Ense&nacute;e a su hijo la canci&oacute;n del ABC.");
nov_es.push("Diga una palabra a su hijo y que &eacute;l / ella pida que busque palabras que riman.");
nov_es.push("No hay actividad para hoy");
nov_es.push("P&iacute;dale a su ni&nacute;o que haga un dibujo o escribir una nota a un miembro de la familia acerca de algo que &eacute;l / ella est&aacute; agradec_esida por");
nov_es.push("Hacer un collar con hilo dental y cereales como Cheerios ™.");
nov_es.push("No hay actividad para hoy");
nov_es.push("D&iacute;a de la Biblioteca!");
nov_es.push("No hay actividad para hoy");
nov_es.push("No hay actividad para hoy");

var dec_es = new Array();
dec_es.push("Practicar la canci&oacute;n del abecedario.");
dec_es.push("Semana Verde: buscar las cosas que son de color verde esta semana.");
dec_es.push("Ayude a su ni&nacute;o a desarrollar su / su nombre con letras magn&eacute;ticas.");
dec_es.push("No hay actividad para hoy");
dec_es.push("Haga que su hijo practique diciendo su n&uacute;mero de tel&eacute;fono.");
dec_es.push("Ayude a su ni&nacute;o demuestre apr_esecio por escribir una nota de agradec_esimiento.");
dec_es.push("Haga que su hijo practique atando su / sus zapatos, o los zapatos de otra persona");
dec_es.push("Hanukkah comienza en el ocaso ");
dec_es.push("No hay actividad para hoy");
dec_es.push("Ayude a su hijo a escribir las letras de su / su nombre de pila. ");
dec_es.push("Haga que su ni&nacute;o escriba su / su nombre en una tarjeta y mostrarla en la puerta de la habitaci&oacute;n");
dec_es.push("Nombre cuatro cosas que riman con 'cat'. No Actividad Para Hoy");
dec_es.push("D&iacute;a de la Biblioteca!");
dec_es.push("Leer un libro favorito de invierno.");
dec_es.push("Haga galletas con su hijo para compartir como un regalo.");
dec_es.push("Cantar una canci&oacute;n favorita de las vacaciones jun_estos.");
dec_es.push("Haga una lista de cosas divertidas que hacer en las vacaciones.");
dec_es.push("No hay actividad para hoy");
dec_es.push("Jugar a un juego que consiste en tomar_es turnos.");
dec_es.push("No hay actividad para hoy");
dec_es.push("Comienza Invierno");
dec_es.push("No hay actividad para hoy");
dec_es.push("No hay actividad para hoy");
dec_es.push("Nochebuena");
dec_es.push("D&iacute;a de Navidad");
dec_es.push("Kwanzaa comienza");
dec_es.push("D&iacute;a de la Biblioteca!");
dec_es.push("Ayude a su hijo a practicar comprimir su / su abrigo y dar un paseo jun_estos.");
dec_es.push("No hay actividad para hoy");
dec_es.push("Cuenta atr&aacute;s! Cuente hacia atr&aacute;s desde 10.");
dec_es.push("Noche Vieja");

var tipsArray_ESP = [jan_es, feb_es, mar_es, apr_es, may_es, jun_es, jul_es, aug_es, sept_es, oct_es, nov_es, dec_es];