/**
Hard coded activity array. Based off united way kindergarten calendar
**/
var jan = new Array();
jan.push("Año Nuevo");
jan.push("Actúe su cuento favorito. Utilice títeres, muñecas o animales de peluche.");
jan.push("Haga que su hijo divida su bocadillo en partes iguales para compartir.");
jan.push("Hoy, lea dos libros");
jan.push("ninguna actividad para hoy");
jan.push("Blue week:look for things that are blue this week.");
jan.push("ninguna actividad para hoy");
jan.push("Cante algunas de las canciones favoritas de su hijo.");
jan.push("ninguna actividad para hoy");
jan.push("¡Día para ir a la Biblioteca!");
jan.push("Juegue Simón dice (Simon Says).");
jan.push("Juegue juegos de contar como \"¿Cuántas cosas azules ves tu?\"");
jan.push("Ayudele a su hijo a hacer su sandwich favorito.");
jan.push("ninguna actividad para hoy");
jan.push("Continúe ense-ñándole a su hijo su número de teléfono y domicilio");
jan.push("ninguna actividad para hoy");
jan.push("Enséñele a su hijo a jugar un juego de mesa con un amigo.");
jan.push("Haga juntos una alcancía con una lata de café y comiencen a ahorrar monedas.");
jan.push("Recite rimas infantiles con su hijo.");
jan.push("Encuentre cosas en la casa que comiencen con el mismo sonido de la letra. Nombre la letra.");
jan.push("Dia de Martin Luther King, Jr");
jan.push("Juegue \"Yo espío (I Spy) números\"");
jan.push("ninguna actividad para hoy");
jan.push("¡Día para ir a la Biblioteca!");
jan.push("ninguna actividad para hoy");
jan.push("Haga o dibuje un hombre de nieve con su hijo.");
jan.push("Usando un artí-culo del periódico, circule las palabras que comiencen con la primera letra del nombre de su hijo");
jan.push("ninguna actividad para hoy");
jan.push("Practique a contar hasta el 10 o más alto.");
jan.push("ninguna actividad para hoy");
jan.push("ninguna actividad para hoy");

var feb = new Array();
feb.push("Lea un libro sobre los sentimientos");
feb.push("El Día de la Marmota (Groundhog Day)");
feb.push("Semana roja: esta semana busque cosas que son de color rojo.");
feb.push("Encuentre cosas en la casa que comiencen con el sonido de la letra \"M\"");
feb.push("inguna actividad para hoy");
feb.push("Haga una lista de personas que usted ama y hable acerca de por qué los ama.");
feb.push("¡Día para ir a la Biblioteca");
feb.push("Haga y mande cartas de San Valentín hechas en casa a sus seres queridos que estan en su lista.Lea un libro sobre los sentimientos ¡Abríguese!");
feb.push("inguna actividad para hoy");
feb.push("Año Nuevo Chino");
feb.push("Haga títeres con bolsas de papel o calcetines y realice una actividad divertida actuando");
feb.push("Cumpleaños de Lincoln ");
feb.push("Lea un cuento y pregúntele a su hijo cual fue la parte favorita de él/ella y por qué.");
feb.push("Día de San Valentín");
feb.push("¡Abríguese! Lleve a su hijo a caminar e invite a un amigo");
feb.push("Cuente todas las puertas y ventanas de su casa.");
feb.push("Juegue con su hijo un juego de mesa o un juego de cartas.");
feb.push("Cumpleaños de Washington <br>Día de los Presidentes");
feb.push("Cante la canción del abecedario. ");
feb.push("Haga que su hijo invite a un amigo a jugar");
feb.push("¡Día para ir a la Biblioteca!");
feb.push("inguna actividad para hoy");
feb.push("Mire afuera y hable sobre lo que ve");
feb.push("Recuerde chequear con su escuela las fechas para la inscripción del kinder (Kindergarten)");
feb.push("inguna actividad para hoy");
feb.push("inguna actividad para hoy");
feb.push("Invite a un amigo para que asista con usted al evento de \"Read Across America\" en el Lincoln Square.");
feb.push("inguna actividad para hoy");
feb.push("inguna actividad para hoy");

var mar = new Array();
mar.push("Escuche con su hijo un cuento en un casete o en un CD.");
mar.push("El evento \"Read Across America\"");
mar.push("Semana morada: esta semana busque cosas que son de color morado");
mar.push("Pídale a su hijo que practique brincar, saltar en un pie y lanzar y capturar una pelota.");
mar.push("Programe para su hijo un examen físico y dental para el Kindergarten.");
mar.push("inguna actividad para hoy");
mar.push("¡Día para ir a la Biblioteca!");
mar.push("Continúe ense-ñándole a su hijo su número de teléfono y domicilio.");
mar.push("inguna actividad para hoy");
mar.push("Daylight Savings Time Begins<br>Turn clocks one hour forward");
mar.push("Sing songs with rhyming sounds.");
mar.push("Name a letter and have your child find items beginning with that sound.");
mar.push("Cut out shapes and play a matching game.");
mar.push("Make up silly words that rhyme with your child\'s name.");
mar.push("Read two books today. Have your child tell you which is his/her favorite and why");
mar.push("inguna actividad para hoy");
mar.push("St. Patrick\'s Day");
mar.push("Find things around the home that begin with the sound of the letter \"J.\"inguna actividad para hoy");
mar.push("inguna actividad para hoy");
mar.push("Spring Begins<br>Take a walk and look for signs of spring.");
mar.push("Library Day!");
mar.push("inguna actividad para hoy");
mar.push("Practice opposites with your child (up/down, in/out, over/under)");
mar.push("inguna actividad para hoy");
mar.push("Passover begins at sunset");
mar.push("Find things that begin with the sound of the letter \"D.\"inguna actividad para hoy");
mar.push("Act out going to the doctor or dentist. Talk about what might happen.");
mar.push("Bake cookies together. Count the number on each tray");
mar.push("Good Friday ");
mar.push("inguna actividad para hoy");
mar.push("Easter Sunday ");

var apr = new Array();
apr.push("April Fools\' Day<br>Easter Monday");
apr.push("Keep the TV off today. Read books and play games instead.");
apr.push("inguna actividad para hoy");
apr.push("Library Day!<br>Bring a friend to the library and check out a movie together.");
apr.push("Have your child name letters found on cereal boxes, cans, etc.");
apr.push("inguna actividad para hoy");
apr.push("Visit the PBS web site: www.pbskids.org.");
apr.push("Draw a picture of spring.");
apr.push("inguna actividad para hoy");
apr.push("inguna actividad para hoy");
apr.push("inguna actividad para hoy");
apr.push("inguna actividad para hoy");
apr.push("Practice printing by tracing the letters of your child\'s name on a piece of paper.");
apr.push("Week of the Young Child begins");
apr.push("Ask your Library Day!librarian to recommend new children\'s music.");
apr.push("inguna actividad para hoy");
apr.push("Visit www.pbs.org/parents and click on the “Fun and Games” tab.");
apr.push("Libary Day!<br>Let your child pick out a video the whole family will enjoy.");
apr.push("Read two books today. Have your child choose the books.");
apr.push("Sing a favorite song with your child.");
apr.push("inguna actividad para hoy");
apr.push("Earth Day");
apr.push("Watch TV with your child, talk about what you see and feel, and ask questions.");
apr.push("Put on music and dance and clap to the beat.");
apr.push("inguna actividad para hoy");
apr.push("inguna actividad para hoy");
apr.push("Have your child begin to learn his/her birth date and age.");
apr.push("Pink week: look for things that are pink this week.");
apr.push("Take a walk and talk about the different sounds you hear");
apr.push("inguna actividad para hoy");
apr.push("inguna actividad para hoy");

var may = new Array();
may.push("inguna actividad para hoy");
may.push("Library Day!");
may.push("Play Simon Says. Focus on exercise activities (hopping, bending over, touching toes).");
may.push("inguna actividad para hoy");
may.push("Cinco de Mayo");
may.push("Find things around the house that are square, circular, and rectangular.");
may.push("inguna actividad para hoy");
may.push("Find things that begin with the sound of the letter \"L.\" Say the name of the letter.");
may.push("Make up nonsense rhymes and laugh together.");
may.push("Name words that rhyme with \"can\".");
may.push("inguna actividad para hoy");
may.push("Mother\'s Day");
may.push("inguna actividad para hoy");
may.push("Help your child write his/her name.");
may.push("inguna actividad para hoy");
may.push("Library Day!");
may.push("Sort coins into groups by color or size.");
may.push("inguna actividad para hoy");
may.push("Count from 1 to 10 or as high as your child can count.");
may.push("Help your child practice shoe tying.");
may.push("inguna actividad para hoy");
may.push("After listening to a story, have your child tell you what happened first, next, and last.");
may.push("Play \"I Spy.\" (Remember to include black objects.)");
may.push("Practice the ABC song.");
may.push("Play a game together such as Memory or Go Fish.");
may.push("Black week: look for things that are black this week.");
may.push("Memorial Day");
may.push("inguna actividad para hoy");
may.push("Look through old magazines and cut out circles, squares, and rectangles.");
may.push("Library Day!");
may.push("inguna actividad para hoy");

var jun = new Array();
jun.push("Find things that begin with the sound of the letter \"S.\"inguna actividad para hoy");
jun.push("White week: look for things that are white this week.");
jun.push("inguna actividad para hoy");
jun.push("Reminder: Did you schedule a kindergarten physical and dental exam?");
jun.push("Plant flowers together in a pot or in the ground and water the flowers.");
jun.push("Go outside and ask your child to repeat patterns: step-step-jump, clap-clap-pat, etc.");
jun.push("Have your child talk about the steps in the planting project.");
jun.push("inguna actividad para hoy");
jun.push("Start a nursery rhyme and have your child finish it.");
jun.push("Have your child invite a friend over to play.");
jun.push("inguna actividad para hoy");
jun.push("Cut up an old greeting card in puzzle-like shapes. Ask your child to fit the pieces back together.");
jun.push("Libary Day!");
jun.push("Flag Day");
jun.push("Make a picnic lunch with your child and eat outside.");
jun.push("Father\'s Day");
jun.push("As you pick out fruits and vegetables at the grocery store, have your child name the colors.");
jun.push("inguna actividad para hoy");
jun.push("Read a story to your child. Point to each word as you read.");
jun.push("Count groups of ten using cereal like Cheerios&#0153");
jun.push("Summer begins");
jun.push("Draw a picture of fun things to do in the summer.");
jun.push("inguna actividad para hoy");
jun.push("inguna actividad para hoy");
jun.push("Have your child match socks as you fold laundry");
jun.push("Practice your phone number and address.");
jun.push("Library Day!");
jun.push("inguna actividad para hoy");
jun.push("inguna actividad para hoy");
jun.push("inguna actividad para hoy");
jun.push("inguna actividad para hoy");

var jul = new Array();
jul.push("inguna actividad para hoy");
jul.push("Find things that begin with the sound of the letter \"T.\"inguna actividad para hoy");
jul.push("inguna actividad para hoy");
jul.push("Independence Day");
jul.push("Pick two books to read today.");
jul.push("Have your child find things that are his/her favorite color.");
jul.push("inguna actividad para hoy");
jul.push("inguna actividad para hoy");
jul.push("Take a walk and count the trees or other things you see.");
jul.push("inguna actividad para hoy");
jul.push("Library Day!");
jul.push("Draw a picture of your family and have your child say the first and last names of each member.");
jul.push("inguna actividad para hoy");
jul.push("inguna actividad para hoy");
jul.push("Practice writing letters and numbers.");
jul.push("Find objects that rhyme with \"pig.\"");
jul.push("inguna actividad para hoy");
jul.push("Have your child retell a story or event in order (first, middle, last).");
jul.push("inguna actividad para hoy");
jul.push("inguna actividad para hoy");
jul.push("Read and talk about people from other cultures.");
jul.push("Count pennies…count as high as you can.");
jul.push("inguna actividad para hoy");
jul.push("Have your child invite a friend over to play");
jul.push("Library Day!");
jul.push("inguna actividad para hoy");
jul.push("Practice naming opposites, like up/down, on/off, etc.");
jul.push("inguna actividad para hoy");
jul.push("Go outside and play Hopscotch or swing.");
jul.push("inguna actividad para hoy");
jul.push("inguna actividad para hoy");

var aug = new Array();
aug.push("inguna actividad para hoy");
aug.push("Look for things that begin with \"P.\" Point out the letter \"P\" in print.");
aug.push("inguna actividad para hoy");
aug.push("Play \"I Spy Colors.\"inguna actividad para hoy");
aug.push("Practice zipping and buttoning.");
aug.push("Read a book about going to school and ask your child to retell the story");
aug.push("Visit your new school and play on the playground.");
aug.push("Library Day!");
aug.push("Find words that rhyme with \"me\".");
aug.push("inguna actividad para hoy");
aug.push("Pretend it is the first day of school. Practice ways to say goodbye.");
aug.push("Practice bouncing a ball. Count the number of bounces.");
aug.push("Organize what your child will need for the first day of school.");
aug.push("Practice taking turns and sharing.");
aug.push("Help your child write his/her name and identify each letter.");
aug.push("inguna actividad para hoy");
aug.push("inguna actividad para hoy");
aug.push("Practice your phone number and address with your child.");
aug.push("inguna actividad para hoy");
aug.push("Draw a picture of your new school.");
aug.push("inguna actividad para hoy");
aug.push("Library Day!");
aug.push("inguna actividad para hoy");
aug.push("inguna actividad para hoy");
aug.push("inguna actividad para hoy");
aug.push("Use addition and subtraction words like \"I have one cookie and you have two cookies. That makes three cookies.\"inguna actividad para hoy");
aug.push("inguna actividad para hoy");
aug.push("inguna actividad para hoy");
aug.push("Put together a puzzle with your child.");
aug.push("inguna actividad para hoy");
aug.push("inguna actividad para hoy");

var sept = new Array();
sept.push("inguna actividad para hoy");
sept.push("Yellow week:look for things that are yellow this week.");
sept.push("Labor Day!");
sept.push("Play a board game or card game with your child.");
sept.push("Help your child write his/her name");
sept.push("inguna actividad para hoy");
sept.push("inguna actividad para hoy");
sept.push("inguna actividad para hoy");
sept.push("Granparents' Day");
sept.push("Look for words that begin with the same first letter using books, magazines and newspaper.");
sept.push("Patriot Day<br>Visit the Farmer's Market at 201 W Kenyon in Champaign(1-5:30pm).");
sept.push("Pick a new book and encourage your child to guess what the story will be about by looking at the cover.");
sept.push("Library Day!  Take your child to the library and get a library card.");
sept.push("inguna actividad para hoy");
sept.push("Go for a walk with your child. Talk about what you see.");
sept.push("Rosh Hashanah begins at sundown.");
sept.push("Find food items or animals that begin with the same sound. Name the letter.");
sept.push("Visit the Farmer's Market at 201 W Kenyon in Champaign(1-5:30pm).");
sept.push("inguna actividad para hoy");
sept.push("inguna actividad para hoy");
sept.push("inguna actividad para hoy");
sept.push("Autumn Begins");
sept.push("inguna actividad para hoy");
sept.push("Practice counting from 1 to 10.");
sept.push("Yom Kippur begins at sundown");
sept.push("inguna actividad para hoy");
sept.push("Library Day!<br>Have your child invite a friend to the library.");
sept.push("Look through magazines and books to find things that are yellow.");
sept.push("inguna actividad para hoy");

var oct = new Array();
oct.push("Child Health Day");
oct.push("Talk about fall and have your child draw a picture of a tree.");
oct.push("inguna actividad para hoy");
oct.push("Cut shapes out of paper to make a picture.");
oct.push("While outdoors,allow your child to draw on the sidewalk with chalk.");
oct.push("Go with your child to buy writing and drawing supplies.");
oct.push("Orange week: look for things that are orange this week.");
oct.push("Columbus Day");
oct.push("Cut pictures of expensive faces from magazines and make a feeling collage.");
oct.push("inguna actividad para hoy");
oct.push("Library Day!");
oct.push("inguna actividad para hoy");
oct.push("Take your child for a walk and collect different kinds of leaves.");
oct.push("Read your favorite children's book to your child.");
oct.push("inguna actividad para hoy");
oct.push("Visit the Farmer's Market at 201 W Kenyon in Champaign (1-5:30pm).");
oct.push("Write a note with your child to a grand-parent, relative or friend.");
oct.push("Sort or count things like socks, canned,soups,buttons, etc.");
oct.push("inguna actividad para hoy");
oct.push("Arrange a play date for your child.");
oct.push("Show your child how to write his/her name using upper and lower case letters.");
oct.push("Make a grocery shopping list together.");
oct.push("Find food items or animals that begin with the same sound as your child's first name.Name the letter.");
oct.push("inguna actividad para hoy");
oct.push("Library Day!");
oct.push("Look at the pictures in a book with your child before reading");
oct.push("inguna actividad para hoy");
oct.push("inguna actividad para hoy");
oct.push("inguna actividad para hoy");
oct.push("Visit the Farmer's Market at 201 W Kenyon in Champaign(1-5:30pm)");
oct.push("Halloween");

var nov = new Array();
nov.push("All Saints' Day!<br>Help your child begin to learn his/her address and phone");
nov.push("inguna actividad para hoy");
nov.push("Help your child draw a picture of your family.");
nov.push("Daylight Savings Time Ends!  Turn clockers back one hour.");
nov.push("Have your child tell a story to a family member.");
nov.push("Election Day");
nov.push("Take a walk. Find things that are brown.");
nov.push("Put on some music and dance with your child and a friend or other family members.");
nov.push("Brown week:look for thing that are brown this week.");
nov.push("Schedule a play date at a park");
nov.push("Veterans Day");
nov.push("Exercise with your child. Count the number of arm circles or hops.");
nov.push("Play Hopscotch with your child.");
nov.push("Ask your child to help set the table and count the items.");
nov.push("Library Day!");
nov.push("inguna actividad para hoy");
nov.push("Go outside and kick a ball back and forth with your child.");
nov.push("Go to the grocery store and have your child help pick items for Thanksgiving.");
nov.push("Look in books, magazines for different facial expressions: happy, sad, excited, scared, etc.");
nov.push("inguna actividad para hoy");
nov.push("Make a picture or decoration for Thanksgiving.");
nov.push("Thanksgiving Day");
nov.push("Teach your child the ABC song.");
nov.push("Say a word to your child and ask him/her to say words that rhyme.");
nov.push("inguna actividad para hoy");
nov.push("Have your child draw a picture or write a note to a family member about something he/she is thankful for");
nov.push("Make a necklace using dental floss and cereal like Cheerios&#0153.");
nov.push("inguna actividad para hoy");
nov.push("Library Day!");
nov.push("inguna actividad para hoy");
nov.push("inguna actividad para hoy");

var dec = new Array();
dec.push("Practice the ABC song.");
dec.push("Green week: look for things that are green this week.");
dec.push("Help your child build his/her name using magnetic letters.");
dec.push("inguna actividad para hoy");
dec.push("Have your child practice saying your phone number.");
dec.push("Help your child show appreciation by writing a thank you note.");
dec.push("Have your child practice tying his/her shoes or the shoes of someone else");
dec.push("Hanukkah begins at sundown ");
dec.push("inguna actividad para hoy");
dec.push("Help your child write the letters of his/her first name. ");
dec.push("Have your child write his/her name on a card and display it on the bedroom door");
dec.push("Name four things that rhyme with \"cat.\"inguna actividad para hoy");
dec.push("Library Day!");
dec.push("Read a favorite winter book.");
dec.push("Make cookies with your child to share as a gift.");
dec.push("Sing a favorite holiday song together.");
dec.push("Make a list of fun things to do over the holidays.");
dec.push("inguna actividad para hoy");
dec.push("Play a game that involves taking turns.");
dec.push("inguna actividad para hoy");
dec.push("Winter begins");
dec.push("inguna actividad para hoy");
dec.push("inguna actividad para hoy");
dec.push("Christmas Eve");
dec.push("Christmas Day");
dec.push("Kwanzaa begins");
dec.push("Library Day!");
dec.push("Help your child practice zipping his/her coat and take a walk together.");
dec.push("inguna actividad para hoy");
dec.push("Countdown! Count backwards from 10.");
dec.push("New Year\'s Eve");

var tipsArray_spanish = [jan, feb, mar, apr, may, jun, jul, aug, sept, oct, nov, dec];