var healthTasks_es = new Array();
healthTasks_es.push("Come una dieta balanceada");
healthTasks_es.push("Obtiene mucho descanso");
healthTasks_es.push("Recibe atenci&oacute;n m&eacute;dica y dental regular");
healthTasks_es.push("Ha recibido todas las vacunas necesarias");
healthTasks_es.push("Corre, salta, juega al aire libre y hace otras actividades que proporcionan ejercicio y ayudan a desarrollar los m&uacute;sculos grandes");
healthTasks_es.push("Trabaja con rompecabezas, hace garabatos, colorea, pinta y hace otras actividades que ayudan a desarrollar los m&uacute;sculos peque&nacute;os");

var languageTasks_es = new Array();
languageTasks_es.push("Tiene muchas oportunidades para hablar y escuchar ");
languageTasks_es.push("Se le lee todos los d&iacute;as");
languageTasks_es.push("Tiene acceso a libros y otros materiales de lectura ");
languageTasks_es.push("Est&aacute; aprendiendo sobre libros y escritura ");
languageTasks_es.push("La televisi&oacute;n es supervisado por un adulto cuando su hijo est&aacute; viendo ");
languageTasks_es.push("Se le anima a hacer preguntas ");
languageTasks_es.push("Se le anima a resolver problemas ");
languageTasks_es.push("Tiene oportunidades para notar similitudes y diferencias ");
languageTasks_es.push("Se le anima a ordenar y clasificar las cosas ");
languageTasks_es.push("Est&aacute; aprendiendo a escribir su nombre y direcci&oacute;n ");
languageTasks_es.push("Est&aacute; aprendiendo a contar y juega juegos de contar");
languageTasks_es.push("Est&aacute; aprendiendo a identificar y nombrar formas y colores");
languageTasks_es.push("Tiene oportunidades de dibujar y ser creativo");
languageTasks_es.push("Tiene la oportunidad de escuchar y hacer m&uacute;sica y bailar");
languageTasks_es.push("Tiene oportunidades de obtener experiencias de primera mano y de hacer las cosas en el mundo - para ver y tocar objetos, escuchar nuevos sonidos, oler y probar comidas y ver cosas en movimiento");

var socialTasks_es = new Array();
socialTasks_es.push("Est&aacute; aprendiendo a explorar y probar cosas nuevas");
socialTasks_es.push("Est&aacute; aprendiendo a trabajar bien solo y hacer muchas tareas de forma independiente");
socialTasks_es.push("Tiene muchas oportunidades de estar con otros ni&nacute;os y est&aacute; aprendiendo a cooperar con ellos");
socialTasks_es.push("Es curioso y motivado a aprender");
socialTasks_es.push("Est&aacute; aprendiendo a terminar tareas");
socialTasks_es.push("Est&aacute; aprendiendo a usar el autocontrol");
socialTasks_es.push("Puede seguir instrucciones simples");
socialTasks_es.push("Ayuda con las tareas familiares");
socialTasks_es.push("Est&aacute; aprendiendo a usar palabras para identificar y expresar emociones");

var otherTasks_es = new Array();
otherTasks_es.push("Escucha cuentos sin interrumpir");
otherTasks_es.push("Reconoce los sonidos que riman");
otherTasks_es.push("Preste atenci&oacute;n por per&iacute;odos cortos de tiempo a las tareas dirigidas por adultos");
otherTasks_es.push("Entiende que las acciones tienen ambas causas y efectos");
otherTasks_es.push("Muestra comprensi&oacute;n de los tiempos generales de d&iacute;a");
otherTasks_es.push("Corta con tijeras");
otherTasks_es.push("Traza formas b&aacute;sicas");
otherTasks_es.push("Empieza a compartir con los dem&aacute;s");
otherTasks_es.push("Comienza a seguir reglas");
otherTasks_es.push("Es capaz de reconocer la autoridad");
otherTasks_es.push("Gestione necesidades de ba&nacute;o");
otherTasks_es.push("Abrocha camisetas, pantalones y abrigos, y cierra la cremallera de cremalleras ");
otherTasks_es.push("Comienza a controlarse");
otherTasks_es.push("Se separa de los padres sin ser molesto");
otherTasks_es.push("Hable comprensible");
otherTasks_es.push("Habla en oraciones completas de entre cinco y seis palabras");
otherTasks_es.push("Mira fotos y luego contar historias");
otherTasks_es.push("Identifica palabras que riman");
otherTasks_es.push("Identifica el sonido inicial de algunas palabras");
otherTasks_es.push("Identifica algunas letras del alfabeto");
otherTasks_es.push("Reconoce algunas palabras comunes a la vista como el 'stop'");
otherTasks_es.push("Ordena objetos similares en color, tama&nacute;o y forma");
otherTasks_es.push("Reconoce grupos de uno, dos, tres, cuatro y cinco objetos");
otherTasks_es.push("Cuenta hasta diez");
otherTasks_es.push("Rebota una pelota");