var healthTasks_es = new Array();
healthTasks_es.push("Come una dieta balanceada");
healthTasks_es.push("Obtiene mucho descanso");
healthTasks_es.push("Recibe atenci&oacute;n m&eacute;dica y dental regular");
healthTasks_es.push("Ha recibido todas las vacunas necesarias");
healthTasks_es.push("Corre, salta, juega al aire libre y hace otras actividades que proporcionan ejercicio y ayudan a desarrollar los m&uacute;sculos grandes");
healthTasks_es.push("Obras rompecabezas, hace garabatos, colorea, pinta y hace otras actividades que ayudan a desarrollar los m&uacute;sculos peque&nacute;os");

var languageTasks_es = new Array();
languageTasks_es.push("Tiene muchas oportunidades para hablar y escuchar");
languageTasks_es.push("Se le lee todos los d&iacute;as ");
languageTasks_es.push("Tiene acceso a libros y otros materiales de lectura ");
languageTasks_es.push("Est&aacute; aprendiendo sobre libros y escritura ");
languageTasks_es.push("La televisi&oacute;n ha supervisado por un adulto ");
languageTasks_es.push("Se le anima a hacer preguntas ");
languageTasks_es.push("Se le anima a resolver los problemas ");
languageTasks_es.push("Tiene oportunidades para notar las similitudes y diferencias ");
languageTasks_es.push("Se le anima a ordenar y clasificar las cosas ");
languageTasks_es.push("Est&aacute; aprendiendo a escribir su / su nombre y direcci&oacute;n ");
languageTasks_es.push("Est&aacute; aprendiendo a contar y juega juegos de contar");
languageTasks_es.push("Est&aacute; aprendiendo a identificar y nombrar formas y colores");
languageTasks_es.push("Tiene oportunidades de dibujar y ser creativos");
languageTasks_es.push("Tiene la oportunidad de escuchar y hacer m&uacute;sica y bailar");
languageTasks_es.push("Tiene oportunidades de obtener experiencias de primera mano y de hacer las cosas en el mundo - para ver y tocar objetos, escuchar nuevos sonidos, oler y probar comidas y ver las cosas se mueven");

var socialTasks_es = new Array();
socialTasks_es.push("Est&aacute; aprendiendo a explorar y probar cosas nuevas");
socialTasks_es.push("Est&aacute; aprendiendo a trabajar bien solo y hacer muchas tareas de forma independiente");
socialTasks_es.push("Tiene muchas oportunidades de estar con otros ni&nacute;os y est&aacute; aprendiendo a cooperar con ellos");
socialTasks_es.push("Es curioso y motivado para aprender");
socialTasks_es.push("Est&aacute; aprendiendo a terminar las tareas");
socialTasks_es.push("Est&aacute; aprendiendo a usar el autocontrol");
socialTasks_es.push("Puede seguir instrucciones simples");
socialTasks_es.push("Ayuda con las tareas familiares");
socialTasks_es.push("Est&aacute; aprendiendo a usar palabras para identificar y expresar emociones");

var otherTasks_es = new Array();
otherTasks_es.push("Escuchar cuentos sin interrumpir");
otherTasks_es.push("Reconocer los sonidos que riman");
otherTasks_es.push("Preste atenci&oacute;n por per&iacute;odos cortos de tiempo a las tareas dirigidas por adultos");
otherTasks_es.push("Comprender que las acciones tienen tanto las causas como los efectos");
otherTasks_es.push("Mostrar comprensi&oacute;n de los tiempos generales de d&iacute;a");
otherTasks_es.push("Cortar con tijeras");
otherTasks_es.push("Trazar formas b&aacute;sicas");
otherTasks_es.push("Comenzar a compartir con los dem&aacute;s");
otherTasks_es.push("Comience a seguir las reglas");
otherTasks_es.push("Ser capaz de reconocer la autoridad");
otherTasks_es.push("Gestione necesidades ba&nacute;o");
otherTasks_es.push("Camiseta, pantalones y abrigos, y las cremalleras hasta postales");
otherTasks_es.push("Empezar a controlarse a s&iacute; mismo");
otherTasks_es.push("A parte de los padres sin ser molesto");
otherTasks_es.push("Hable comprensible");
otherTasks_es.push("Habla en oraciones completas de entre cinco y seis palabras");
otherTasks_es.push("Mira fotos y luego contar historias");
otherTasks_es.push("Identificar palabras que riman");
otherTasks_es.push("Identificar el sonido inicial de algunas palabras");
otherTasks_es.push("Identificar algunas letras del alfabeto");
otherTasks_es.push("Reconocer algunas palabras comunes a la vista como el 'stop'");
otherTasks_es.push("Ordena objetos similares en color, tama&nacute;o y forma");
otherTasks_es.push("Reconocer los grupos de uno, dos, tres, cuatro y cinco objetos");
otherTasks_es.push("Cuenta hasta diez");
otherTasks_es.push("Rebotar una pelota");