<?php

$events = array
(
	//jan
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//feb
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//mar
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//apr
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//may
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//jun
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//jul
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","Go snowboarding<br>Go to the beach<br>Go to the playground<br>Go to the mall<br>Go to the supermarket<br>Kite flying day<br>Movie Day<br>Make a clay cup<br>Meet a pet<br>Meet new friends","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//aug
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//sept
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//oct
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//nov
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee"),
	//dec
array("a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x",
	"y","z","aa","bb","cc","dd","ee")
);
?>
